/**
 * Built-in grid preset tabs.
 * Each tab is an ordered list of { filterId, presetName } pairs.
 */
export const BUILTIN_TABS = [
  {
    id: 'overview',
    name: 'Overview',
    tiles: [
      { filterId: 'autodetect', presetName: 'All' },
      { filterId: 'channel',    presetName: 'Red' },
      { filterId: 'channel',    presetName: 'Green' },
      { filterId: 'channel',    presetName: 'Blue' },
      { filterId: 'bitplane',   presetName: 'Alpha Bit 0' },
      { filterId: 'ela',        presetName: 'High Quality (95)' },
      { filterId: 'noise',      presetName: 'Soft' },
      { filterId: 'gradient',   presetName: 'Both' },
      { filterId: 'hsv',        presetName: 'Hue' },
      { filterId: 'metadata',   presetName: 'All' },
    ],
  },
  {
    id: 'color',
    name: 'Color',
    tiles: [
      { filterId: 'channel',  presetName: 'Red' },
      { filterId: 'channel',  presetName: 'Green' },
      { filterId: 'channel',  presetName: 'Blue' },
      { filterId: 'channel',  presetName: 'Alpha' },
      { filterId: 'hsv',      presetName: 'Hue' },
      { filterId: 'hsv',      presetName: 'Saturation' },
      { filterId: 'hsv',      presetName: 'Value' },
      { filterId: 'lab',      presetName: 'L*' },
      { filterId: 'lab',      presetName: 'a*' },
      { filterId: 'lab',      presetName: 'b*' },
      { filterId: 'pca',      presetName: 'PC1' },
      { filterId: 'pca',      presetName: 'PC2' },
      { filterId: 'pca',      presetName: 'PC3' },
      { filterId: 'colormap', presetName: 'Viridis' },
      { filterId: 'colormap', presetName: 'Inferno' },
      { filterId: 'colormap', presetName: 'Jet' },
      { filterId: 'palette',  presetName: 'File Palette' },
      { filterId: 'palette',  presetName: 'Top 64 Colors' },
    ],
  },
  {
    id: 'compression',
    name: 'Compression',
    tiles: [
      { filterId: 'ela',          presetName: 'Low Quality (65)' },
      { filterId: 'ela',          presetName: 'Medium (80)' },
      { filterId: 'ela',          presetName: 'High Quality (95)' },
      { filterId: 'jpeg-ghost',   presetName: 'Q70' },
      { filterId: 'jpeg-ghost',   presetName: 'Q85' },
      { filterId: 'quantization', presetName: 'All Tables' },
    ],
  },
  {
    id: 'noise',
    name: 'Noise',
    tiles: [
      { filterId: 'noise',     presetName: 'Soft' },
      { filterId: 'noise',     presetName: 'Aggressive' },
      { filterId: 'frequency', presetName: 'High Pass' },
      { filterId: 'frequency', presetName: 'Low Pass' },
      { filterId: 'wavelet',   presetName: 'Residual L1' },
      { filterId: 'histogram', presetName: 'Graph All' },
    ],
  },
  {
    id: 'structure',
    name: 'Structure',
    tiles: [
      { filterId: 'gradient', presetName: 'Both' },
      { filterId: 'gradient', presetName: 'Horizontal' },
      { filterId: 'gradient', presetName: 'Vertical' },
      { filterId: 'clone',    presetName: 'Fast (16px)' },
    ],
  },
  {
    id: 'stego',
    name: 'Steganography',
    tiles: [
      { filterId: 'autodetect',    presetName: 'All' },
      { filterId: 'bitplane',      presetName: 'Alpha Bit 0' },
      { filterId: 'bitplane',      presetName: 'Red Bit 0' },
      { filterId: 'bitplane',      presetName: 'Green Bit 0' },
      { filterId: 'bitplane',      presetName: 'Blue Bit 0' },
      { filterId: 'bitplane',      presetName: 'Luma Bit 0' },
      { filterId: 'bitplane-xor',  presetName: 'G XOR A bit0' },
      { filterId: 'bitplane-xor',  presetName: 'R XOR A bit0' },
      { filterId: 'bitplane-xor',  presetName: 'B XOR A bit0' },
      { filterId: 'bitplane-xor',  presetName: 'R XOR G bit0' },
      { filterId: 'pca',           presetName: 'PC3' },
      { filterId: 'strings',       presetName: 'ASCII ≥6' },
      { filterId: 'chi-square',    presetName: 'Full image' },
      { filterId: 'chi-square',    presetName: 'Top half' },
      { filterId: 'chi-square',    presetName: 'Bottom half' },
      { filterId: 'lsb-extract',   presetName: 'R bit0 row MSB' },
      { filterId: 'lsb-extract',   presetName: 'G bit0 row MSB' },
      { filterId: 'lsb-extract',   presetName: 'B bit0 row MSB' },
      { filterId: 'lsb-extract',   presetName: 'RGB interleaved' },
    ],
  },
  {
    id: 'metadata',
    name: 'Metadata',
    tiles: [
      { filterId: 'metadata',     presetName: 'All' },
      { filterId: 'thumbnail',    presetName: 'Show' },
      { filterId: 'gps',          presetName: 'All' },
      { filterId: 'quantization', presetName: 'All Tables' },
      { filterId: 'strings',      presetName: 'ASCII ≥8' },
      { filterId: 'autodetect',   presetName: 'All' },
      { filterId: 'embedded',     presetName: 'Scan All' },
      { filterId: 'palette',      presetName: 'File Palette' },
    ],
  },
  {
    id: 'analysis',
    name: 'Analysis',
    tiles: [
      { filterId: 'entropy',          presetName: '8×8 blocks'    },
      { filterId: 'entropy',          presetName: '16×16 blocks'  },
      { filterId: 'entropy',          presetName: '32×32 blocks'  },
      { filterId: 'fft',              presetName: 'Luma (log mag)'},
      { filterId: 'fft',              presetName: 'Luma (phase)'  },
      { filterId: 'dct',              presetName: 'AC Energy'     },
      { filterId: 'dct',              presetName: 'High-Freq AC'  },
      { filterId: 'dct',              presetName: 'Avg DCT Block' },
      { filterId: 'byte-histogram',   presetName: 'File Bytes'    },
      { filterId: 'curves',           presetName: 'High Contrast' },
      { filterId: 'curves',           presetName: 'Gamma 0.5'     },
      { filterId: 'curves',           presetName: 'Lift Shadows'  },
    ],
  },
];
